// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_Project.Entity;

namespace School_Project.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210413225116_sp1")]
    partial class sp1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("School_Project.Entity.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AraçMarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AraçModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GörselLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KDVOranı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParaBirimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PiyasaFiyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SevkiyatSüresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokAdedi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrendyolFiyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ÜrünAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
